### ISSUE TITLE
Allow annotations for specifying fields instead of class attributes

### ISSUE THREAD

**Issue by Kylebrown9** [rossmacarthur/serde#99]
The new `typing.NamedTuple` class offers a new way to specify named tuples using colon based type labels.

I would like this syntax to be available for defining model classes so that the Dog example in the README can be written like this

```python
class Dog(Model):
     name: fields.Str()
     hates_cats: fields.Optional(fields.Bool, default=True)
```

Reference:
https://docs.python.org/3/library/typing.html#typing.NamedTuple

**Comment by rossmacarthur** [comment]
Thanks for the suggestion. This looks pretty easy to implement (they simply end up in a class attribute `__annotations__`). I think the only question that would need to be resolved is what happens in cases where both are used. 

For example:

```python
class Dog(Model):
    name: fields.Str()
    name = fields.Int()
```

or

```python
class Dog(Model):
    name: fields.Str()
    name = 'hello'
```

or even just a mix

```python
class Dog(Model):
    name: fields.Str()
    hates_cats = fields.Bool()
```


- If annotations are used should we ignore any further class attributes?
- Does the one override the other? I.e. if annotations and class attributes assign an identically named attribute which has priority then?
- Do we error if both are used?

**Comment by rossmacarthur** [comment]
Additionally I think it would be fine for these annotations used the same "resolving" of types and model classes into fields that are used for container fields like `fields.Dict`. So you would be able to do something like this

```python
class Dog(Model):
    name: str
    hates_cats: bool
```

**Comment by Kylebrown9** [comment]
Thanks, this looks like it's headed where I was hoping it would.
